# Generated by Django 4.0.1 on 2022-03-28 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_admission_name_prov_alter_advertisement_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Введите стоимость заказа', verbose_name='Стоимость заказа')),
                ('full_name', models.CharField(help_text='Введите ФИО заказчика', max_length=150, verbose_name='ФИО заказчика')),
                ('address', models.CharField(help_text='Введите адрес заказчика', max_length=200, verbose_name='Адрес заказчика')),
                ('order_date', models.DateField(default=datetime.date.today, help_text='Выберите дату заказа', verbose_name='Дата заказа')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(help_text='Введите стоимость книги', verbose_name='Стоимость книги')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text='Введите тип переплета', max_length=50, null=True, verbose_name='Тип переплета')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите статус экземпляра книги', max_length=20, null=True, verbose_name='Статус экземпляра книги')),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='book_for_sale',
        ),
        migrations.RemoveField(
            model_name='check',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='location',
            name='num_dep',
        ),
        migrations.RemoveField(
            model_name='book',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Введите отчество автора', max_length=100, null=True, verbose_name='Отчество автора'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Введите краткое описание книги', max_length=1750, null=True, verbose_name='Аннотация книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Введите название книги', max_length=350, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Введите жанр книги', max_length=200, null=True, verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона поставщика', max_length=18, verbose_name='Номер телефона поставщика'),
        ),
        migrations.AlterField(
            model_name='pub_house',
            name='name',
            field=models.CharField(help_text='Введите издательство', max_length=200, null=True, verbose_name='Издательство книги'),
        ),
        migrations.DeleteModel(
            name='Book_for_sale',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Выберите книгу', on_delete=django.db.models.deletion.PROTECT, to='catalog.book', verbose_name='Название книги'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='order_num',
            field=models.ForeignKey(blank=True, help_text='Выберите номер заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.booking', verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='receipt',
            field=models.ForeignKey(help_text='Выберите номер поступления', on_delete=django.db.models.deletion.PROTECT, to='catalog.admission', verbose_name='Номер поступления'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Выберите статус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='booking',
            name='book',
            field=models.ForeignKey(help_text='Выберите книгу', on_delete=django.db.models.deletion.PROTECT, to='catalog.book', verbose_name='Название книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Выберите переплет', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cover', verbose_name='Переплет'),
        ),
    ]
